import asyncio
import httpx

BASE_URL = "http://127.0.0.1:8000/api/v1"


async def run_live_tests():
    print("🧪 Starting End-to-End Live API Tests on Olsson API...\n")
    # Using generous timeout for multi-turn LLM generation
    async with httpx.AsyncClient(base_url=BASE_URL, timeout=120.0) as client:
        # 1. Health Check
        print("1️⃣ Testing Health Check...")
        res = await client.get("/health")
        assert res.status_code == 200, f"Health check failed: {res.text}"
        print("   ✅ Health check passed:", res.json())

        # 2. Start Unverified Chat (Expect Challenge)
        print("\n2️⃣ Testing Unverified Chat (Security Challenge)...")
        res = await client.post("/chat", json={"message": "Hey Olsson!"})
        assert res.status_code == 200, f"Chat challenge failed: {res.text}"
        data = res.json()
        session_id = data["session_id"]
        assert data["is_verified"] is False
        assert "Identity Verification Required" in data["content"]
        print("   ✅ Security challenge received for session:", session_id)

        # 3. Verify Identity with Fred's DOB / Girlfriend name
        print("\n3️⃣ Testing Verification with Girlfriend's Name (Jamirah Najjemba)...")
        res = await client.post("/chat/verify", json={
            "session_id": session_id,
            "answer": "Jamirah Najjemba"
        })
        assert res.status_code == 200, f"Verification failed: {res.text}"
        v_data = res.json()
        assert v_data["is_verified"] is True
        print("   ✅ Identity verification successful:", v_data["message"])

        # 4. Chat in Verified Session (Testing Persona & Memory)
        print("\n4️⃣ Testing Verified Conversation (Persona Check)...")
        res = await client.post("/chat", json={
            "session_id": session_id,
            "message": "Who am I and what stack do I specialize in?",
            "model": "default"
        })
        assert res.status_code == 200, f"Verified chat failed: {res.text}"
        chat_data = res.json()
        first_msg_id = chat_data["message_id"]
        print(f"   ✅ Model Responded ({chat_data['responded_by']}):")
        print("   " + chat_data["content"][:200].replace("\n", " ") + "...")

        # 5. WhatsApp-Style Quote Reply
        print("\n5️⃣ Testing WhatsApp-Style Quote Reply (reply_to_id)...")
        res = await client.post("/chat", json={
            "session_id": session_id,
            "message": "Can you give me a 2-line example in Flutter Dart?",
            "reply_to_id": first_msg_id,
            "model": "default"
        })
        assert res.status_code == 200, f"Quote reply failed: {res.text}"
        reply_data = res.json()
        print(f"   ✅ Quoted reply answered by ({reply_data['responded_by']}):")
        print("   " + reply_data["content"][:180].replace("\n", " ") + "...")

        # 6. Retry Endpoint
        print("\n6️⃣ Testing Retry Endpoint on Last Turn...")
        res = await client.post("/chat/retry", json={
            "session_id": session_id,
            "model": "default"
        })
        assert res.status_code == 200, f"Retry failed: {res.text}"
        retry_data = res.json()
        print(f"   ✅ Retry regenerated by ({retry_data['responded_by']}):")
        print("   " + retry_data["content"][:180].replace("\n", " ") + "...")

        # 7. Session History Retrieval
        print("\n7️⃣ Testing Session History & Persistence...")
        res = await client.get(f"/sessions/{session_id}")
        assert res.status_code == 200, f"Get session failed: {res.text}"
        history_data = res.json()
        assert len(history_data["messages"]) >= 4
        print(f"   ✅ Session history verified ({len(history_data['messages'])} messages stored).")

        # 8. List All Sessions
        print("\n8️⃣ Testing Sessions List...")
        res = await client.get("/sessions")
        assert res.status_code == 200, f"List sessions failed: {res.text}"
        sessions_list = res.json()
        assert len(sessions_list) >= 1
        print(f"   ✅ Found {len(sessions_list)} session(s) in database.")

        print("\n🎉 ALL 8 END-TO-END TESTS PASSED FLAWLESSLY!")


if __name__ == "__main__":
    asyncio.run(run_live_tests())
